### ISSUE TITLE
Install and update fail

### ISSUE THREAD

**Issue by neuwirthe** [csgillespie/efficientR#112]
I managed to install the package from the github repos  about two weeks ago,
but now, when I try to update or reinstall, I get an error:

```
installing to /Library/Frameworks/R.framework/Versions/3.3/Resources/library/efficientR/libs
** data
*** moving datasets to lazyload DB
Warning: file ‘05-f2.RData’ has magic number 'X'
  Use of save versions prior to 2 is deprecated
Error : bad restore file magic number (file may be corrupted) -- no data loaded
ERROR: lazydata failed for package ‘efficientR’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/efficientR’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/efficientR’
Error: Command failed (1)
```

**Comment by claudiof90** [comment]
I have the same problem (my OS is Debian Jessie)!

**Comment by csgillespie** [comment]
@claudiof90 @neuwirthe Thanks for the report. Should be fixed now. 

The issue is that we are abusing (taking advantage?) of R's package system to make it easy to install dependencies. We stored additional data files in "data/" but in an R package, they need to be a certain format (which I forgot a commit or two ago).

@Robinlovelace I've moved data/ to extdata/ and updated paths

**Comment by neuwirthe** [comment]
I already couod finish the update.
Thanks
